version: '3'

services:
  main:
    image: tortoisebot_jenkins:latest 
    container_name: jenkins_checkpoint
    environment: 
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    restart: always